# Generated by Django 5.2 on 2025-05-04 14:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=2000)),
                ('direction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_direction', to='lk1_backend.direction')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(blank=True, max_length=11, null=True)),
                ('telegram', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('vk', models.CharField(blank=True, max_length=100, null=True)),
                ('university', models.CharField(blank=True, max_length=200, null=True)),
                ('institute', models.CharField(blank=True, max_length=200, null=True)),
                ('specialization', models.CharField(blank=True, max_length=100, null=True)),
                ('year_of_study', models.CharField(blank=True, max_length=50, null=True)),
                ('role', models.CharField(choices=[('Проектант', 'Проектант'), ('Куратор', 'Куратор'), ('Организатор', 'Организатор'), ('Руководитель направления', 'Руководитель направления'), ('Администратор', 'Администратор')], default='Проектант', max_length=24)),
                ('description', models.TextField(blank=True, max_length=2000)),
                ('photo', models.ImageField(blank=True, default='default_avatar.jpeg', upload_to='users_photo/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(default='default_avatar.jpeg', upload_to='users_files/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_owner', to='lk1_backend.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('level', models.CharField(choices=[('Базовый', 'Базовый'), ('Средний', 'Средний'), ('Продвинутый', 'Продвинутый')], default=('Базовый', 'Базовый'), max_length=11)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_owner', to='lk1_backend.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams_project', to='lk1_backend.project')),
                ('member1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_member_1', to='lk1_backend.userprofile')),
                ('member2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_member_2', to='lk1_backend.userprofile')),
                ('member3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_member_3', to='lk1_backend.userprofile')),
                ('member4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_member_4', to='lk1_backend.userprofile')),
                ('member5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_member_5', to='lk1_backend.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='tutor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_tutor', to='lk1_backend.userprofile'),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, max_length=2000)),
                ('status', models.CharField(choices=[('Анонсировано', 'Анонсировано'), ('Началось', 'Началось'), ('Закончилось', 'Закончилось')])),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('number_of_participants', models.IntegerField(default=1)),
                ('direction1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_direction1', to='lk1_backend.direction')),
                ('direction2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_direction2', to='lk1_backend.direction')),
                ('direction3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_direction3', to='lk1_backend.direction')),
                ('organizer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_organizer', to='lk1_backend.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='direction',
            name='director',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direction_director', to='lk1_backend.userprofile'),
        ),
        migrations.CreateModel(
            name='ApllictationToProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Отправлена', 'Отправлена'), ('Принята', 'Принята'), ('Отклонена', 'Отклонена')])),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event', to='lk1_backend.project')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_apllication_sender', to='lk1_backend.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ApllictationToEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Отправлена', 'Отправлена'), ('Принята', 'Принята'), ('Отклонена', 'Отклонена')])),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event', to='lk1_backend.event')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_apllication_sender', to='lk1_backend.userprofile')),
            ],
        ),
    ]
