# Generated by Django 5.2 on 2025-05-05 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lk1_backend', '0002_userprofile_year_of_graduation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectteam',
            name='member1_role',
            field=models.CharField(blank=True, choices=[('Backend-разработчик', 'Backend-разработчик'), ('Frontend-разработчик', 'Frontend-разработчик'), ('Аналитик', 'Аналитик'), ('Дизайнер', 'Дизайнер'), ('Тимлид', 'Тимлид')], max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='projectteam',
            name='member2_role',
            field=models.CharField(blank=True, choices=[('Backend-разработчик', 'Backend-разработчик'), ('Frontend-разработчик', 'Frontend-разработчик'), ('Аналитик', 'Аналитик'), ('Дизайнер', 'Дизайнер'), ('Тимлид', 'Тимлид')], max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='projectteam',
            name='member3_role',
            field=models.CharField(blank=True, choices=[('Backend-разработчик', 'Backend-разработчик'), ('Frontend-разработчик', 'Frontend-разработчик'), ('Аналитик', 'Аналитик'), ('Дизайнер', 'Дизайнер'), ('Тимлид', 'Тимлид')], max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='projectteam',
            name='member4_role',
            field=models.CharField(blank=True, choices=[('Backend-разработчик', 'Backend-разработчик'), ('Frontend-разработчик', 'Frontend-разработчик'), ('Аналитик', 'Аналитик'), ('Дизайнер', 'Дизайнер'), ('Тимлид', 'Тимлид')], max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='projectteam',
            name='member5_role',
            field=models.CharField(blank=True, choices=[('Backend-разработчик', 'Backend-разработчик'), ('Frontend-разработчик', 'Frontend-разработчик'), ('Аналитик', 'Аналитик'), ('Дизайнер', 'Дизайнер'), ('Тимлид', 'Тимлид')], max_length=25, null=True),
        ),
    ]
