# Generated by Django 5.2 on 2025-05-13 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lk1_backend', '0003_projectteam_member1_role_projectteam_member2_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apllictationtoevent',
            name='status',
            field=models.CharField(choices=[('Отправлена', 'Отправлена'), ('Принята', 'Принята'), ('Отклонена', 'Отклонена')], max_length=20),
        ),
        migrations.AlterField(
            model_name='apllictationtoproject',
            name='status',
            field=models.CharField(choices=[('Отправлена', 'Отправлена'), ('Принята', 'Принята'), ('Отклонена', 'Отклонена')], max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('Анонсировано', 'Анонсировано'), ('Началось', 'Началось'), ('Закончилось', 'Закончилось')], max_length=20),
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('Анонсировано', 'Анонсировано'), ('Началось', 'Началось'), ('Закончилось', 'Закончилось')], max_length=20)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meeting_team', to='lk1_backend.projectteam')),
            ],
        ),
    ]
