# Generated by Django 5.2 on 2025-05-13 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lk1_backend', '0004_alter_apllictationtoevent_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='team',
        ),
        migrations.AddField(
            model_name='meeting',
            name='team_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='UserProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_role', models.CharField(blank=True, choices=[('Backend-разработчик', 'Backend-разработчик'), ('Frontend-разработчик', 'Frontend-разработчик'), ('Аналитик', 'Аналитик'), ('Дизайнер', 'Дизайнер'), ('Тимлид', 'Тимлид')], max_length=25, null=True)),
                ('team_name', models.CharField(max_length=50)),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_member', to='lk1_backend.userprofile')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams_project', to='lk1_backend.project')),
            ],
        ),
        migrations.DeleteModel(
            name='ProjectTeam',
        ),
    ]
