# Generated by Django 5.2 on 2025-05-22 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lk1_backend', '0005_remove_meeting_team_meeting_team_name_userproject_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='role',
        ),
        migrations.CreateModel(
            name='MeetingUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_meeting', to='lk1_backend.meeting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_in_meeting', to='lk1_backend.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Проектант', 'Проектант'), ('Куратор', 'Куратор'), ('Организатор', 'Организатор'), ('Руководитель направления', 'Руководитель направления'), ('Администратор', 'Администратор')], default='Проектант', max_length=24)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_owner', to='lk1_backend.userprofile')),
            ],
        ),
    ]
