# Generated by Django 5.2 on 2025-05-22 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lk1_backend', '0006_remove_userprofile_role_meetinguser_userrole'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MeetingUser',
            new_name='UserMeeting',
        ),
    ]
