# Generated by Django 5.2 on 2025-05-22 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lk1_backend', '0007_rename_meetinguser_usermeeting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apllictationtoevent',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_event', to='lk1_backend.event'),
        ),
        migrations.CreateModel(
            name='EventDirection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_direction', to='lk1_backend.direction')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event', to='lk1_backend.event')),
            ],
        ),
    ]
