# Generated by Django 5.2 on 2025-05-22 10:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lk1_backend', '0008_alter_apllictationtoevent_event_eventdirection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='start_date',
        ),
        migrations.AddField(
            model_name='meeting',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meeting',
            name='end_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meeting',
            name='start_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
