# Generated by Django 5.2 on 2025-05-22 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lk1_backend', '0009_remove_meeting_end_date_remove_meeting_start_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='direction1',
        ),
        migrations.RemoveField(
            model_name='event',
            name='direction2',
        ),
        migrations.RemoveField(
            model_name='event',
            name='direction3',
        ),
        migrations.CreateModel(
            name='MeetingTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=50)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_meeting', to='lk1_backend.meeting')),
            ],
        ),
    ]
