# Generated by Django 5.2 on 2025-05-22 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lk1_backend', '0011_eventuser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EventUser',
            new_name='UserEvent',
        ),
    ]
