# Generated by Django 5.2 on 2025-05-23 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lk1_backend', '0012_rename_eventuser_userevent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userproject',
            name='member_role',
        ),
        migrations.AddField(
            model_name='userproject',
            name='member_main_role',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userproject',
            name='member_second_role',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userproject',
            name='member_third_role',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('Анонсировано', 'Анонсировано'), ('Началось', 'Началось'), ('Закончилось', 'Закончилось')], default=('Анонсировано', 'Анонсировано'), max_length=20),
        ),
    ]
