# Generated by Django 5.2 on 2025-05-24 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lk1_backend', '0013_remove_userproject_member_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apllictationtoevent',
            name='status',
            field=models.CharField(choices=[('На рассмотрении', 'На рассмотрении'), ('Принята', 'Принята'), ('Отклонена', 'Отклонена')], max_length=20),
        ),
        migrations.AlterField(
            model_name='apllictationtoproject',
            name='status',
            field=models.CharField(choices=[('На рассмотрении', 'На рассмотрении'), ('Принята', 'Принята'), ('Отклонена', 'Отклонена')], max_length=20),
        ),
    ]
