# Generated by Django 5.2 on 2025-05-24 13:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lk1_backend', '0014_alter_apllictationtoevent_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apllictationtoevent',
            name='send_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apllictationtoproject',
            name='send_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
