# Generated by Django 5.2 on 2025-05-24 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lk1_backend', '0015_apllictationtoevent_send_date_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserRole',
            new_name='UserStatus',
        ),
        migrations.RenameField(
            model_name='userstatus',
            old_name='role',
            new_name='status',
        ),
        migrations.AlterField(
            model_name='apllictationtoevent',
            name='status',
            field=models.CharField(choices=[('На рассмотрении', 'На рассмотрении'), ('Принято', 'Принято'), ('Отклонено', 'Отклонено')], max_length=20),
        ),
        migrations.AlterField(
            model_name='apllictationtoproject',
            name='status',
            field=models.CharField(choices=[('На рассмотрении', 'На рассмотрении'), ('Принято', 'Принято'), ('Отклонено', 'Отклонено')], max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
