# Generated by Django 5.2 on 2025-05-25 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lk1_backend', '0016_rename_userrole_userstatus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfile',
            name='file',
            field=models.FileField(upload_to='users_files/'),
        ),
    ]
